backend:
  name: github
  repo: jonavila/dev-zone

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: docs/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }