backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "docs/blog/{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "date", format: "YYYY-MM-DD" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "image", label: "Image", widget: "image", default: false, required: false }
      - { name: "imageAuthor", label: "Image Author", widget: "string", default: false, required: false }
      - { name: "imageAuthorLink", label: "Image Author Link", widget: "string", default: false, required: false }
      - { name: "showImageInArticle", label: "Show Image in Article", widget: "boolean", default: false, required: false }
      - { name: "canonicalLink", label: "Canonical Link", widget: "string", default: false, required: false }
      - { name: "publishedAt", label: "Published At", widget: "string", default: false, required: false }
      - { name: "excerpt", label: "Excerpt", widget: "text", default: false, required: false }
      - { name: "draft", label: "Draft", widget: "boolean", default: false, required: false }
